image: mcr.microsoft.com/dotnet/sdk:7.0
pipelines:
  default:
      - step:
          name: Build app
          caches:
            - dotnetcore
          script:
          - dotnet restore logger/$SOLUTION_NAME.sln
          - dotnet build --no-restore logger/$SOLUTION_NAME.sln --configuration $CONFIGURATION
  tags:
   "v-*.*.*":
    - step:
        caches:
          - dotnetcore
        script: 
          - export VERSION_NUMBER=${BITBUCKET_TAG/v-/}
          - apt-get update -y
          - apt-get install -y xmlstarlet
          - xmlstarlet ed --inplace -u "//Project//PropertyGroup/Version" -v $VERSION_NUMBER logger/$SOLUTION_NAME.csproj
          - dotnet restore logger/$SOLUTION_NAME.sln
          - dotnet build --no-restore logger/$SOLUTION_NAME.sln --configuration $CONFIGURATION
          - dotnet nuget push logger/bin/$CONFIGURATION/$SOLUTION_NAME.$VERSION_NUMBER.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_KEY
